### ISSUE TITLE
Is there some sample data that can be used to test this framework?

### ISSUE THREAD

**Issue by hunkyu** [kekeliu-whu/Wildcat-SLAM#1]
Is there some sample data that can be used to test this framework?

**Comment by kekeliu-whu** [comment]
This is a demonstration rather than a complete program. It's only adapted for the hilti2022 dataset, and all parameters including extrinsic parameters are hard-coded into the code.

So if you want to test it, I recommend downloading the hilti2022 dataset and testing it by launching run.launch while playing the rosbag data.
